# helm/mlflow/templates/secret.yaml
{{- if not .Values.backend.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-backend
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: {{ .Values.backend.connectionString | quote }}
{{- end }}
